trigger:
- main

pool:
  vmImage: ubunto-latest

variables: 
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
